//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter name.")]
        [StringLength(50)]
        [DisplayName("Họ Tên")]
        public string Name { get; set; }
        [StringLength(50)]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Please enter Phone.")]
        [DisplayName("Điện thoại")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please enter Address.")]
        [DisplayName("Địa chỉ")]
        public string Address { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Please enter Date.")]
        [DisplayName("Ngày sinh")]
        public Nullable<System.DateTime> Date { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Please enter Email.")]
        [DisplayName("Email")]
        public string Email { get; set; }
    }
}
